### ISSUE TITLE
Run instruction issues

### ISSUE THREAD

**Issue by yevagorbachev** [yaruluo/raduckal__yluo00-phuang00-jlin00-ezhang00#5]
The instructions are in a strange order. One would need to more or less already know what they are doing in order to use them.

Running `app/__init__.py` results in exceptions being thrown when visiting `http://localhost:5000/country`. Running `__init__.py` from the `app/` directory works. I would recommend replacing `python app/__init.py__` (which is a typo, as the trailing double underscore should come before the file extension) with `cd app/` and `python3 __init__.py`.

**Comment by jlin00** [comment]
thanks yevgeniy!
